sudo: required

dist: trusty

git:
  depth: 1

addons:
  sonarcloud: true
  apt:
    sources:
     - sourceline: 'deb http://download.mono-project.com/repo/ubuntu trusty main'
       key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF'
    packages:
     - mono-complete
     - dos2unix

jdk:
  - openjdk11

before_install: 
  - wget -O os.deb http://oscript.io/downloads/night-build/deb?bitness=x64
  - sudo dpkg -i os.deb; sudo apt install -f
  - oscript

install: 
  - sudo opm install -l
  - sudo opm install -l 1bdd
  - sudo dos2unix oscript_modules/1bdd/features/lib/step_definitions/ВыполнениеКоманд.os
  - sudo patch oscript_modules/1bdd/features/lib/step_definitions/ВыполнениеКоманд.os 1bdd.patch
  - oscript -make src/cmd/ovm.os ovm.exe
  - echo -e "#!/bin/sh\nmono ./ovm.exe \"\$@\"" > ~/bin/ovm
  - chmod +x ~/bin/ovm
  - ovm

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - ./travis.sh 
